name: FineNet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pyyaml
  - h5py
  - tqdm
  - ipython
  - jupyter_client
  - cython
  - ffmpeg
  - pip
  - pip:
    - torch
    - torchaudio
    - torchvision
    - pytorch-lightning==1.9.5
    - torchmetrics==0.11.4
    - accelerate
    - einops
    - smplx
    - trimesh
    - pyrender
    - opencv-python
    - opencv-contrib-python
    - scikit-learn
    - scikit-image
    - transformers
    - diffusers
    - librosa
    - soundfile
    - moviepy
    - imageio
    - imageio-ffmpeg
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - wandb
    - tensorboard
    - tensorboardx
    - easydict
    - fire
    - ftfy
    - regex
    - pillow
    - plotly
    - gdown
    - huggingface-hub
    - safetensors
    - sentence-transformers
    - pydub
    - json-tricks
    - yacs
    - fvcore
    - iopath
    - tabulate
    - rich
    - click
